service: classifier-api

provider:
  name: aws
  runtime: java8
  stage: dev
  region: us-east-2
  cfLogs: true
  memorySize: 1536
  timeout: 60
  vpc:
      securityGroupIds:
        - sg-87fa1fef
        - sg-133b3a7a
      subnetIds:
        - subnet-91561df8
  iamRoleStatements:
    -  Effect: Allow
       Action: 
         - ec2:CreateNetworkInterface
         - ec2:DescribeNetworkInterfaces
         - ec2:DeleteNetworkInterface
         - logs:CreateLogGroup
         - logs:CreateLogStream
         - logs:PutLogEvents
       Resource: "*"

package:
  artifact: build/distributions/classifier-api.zip

functions:
  users:
    handler: com.classifier.LambdaHandler
    events:
      - http:
          path: classifiers
          method: get
          cors: true
      - http:
          path: classifiers/{classifierId}
          method: get
          cors: true
      - http:
          path: classifiers
          method: post
          cors: true
      - http:
          path: classifiers/translate/{classifierId}/{languageCode}
          method: get
          cors: true
           
